---
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "yes"
security_ssh_x11_forwarding: "no"
security_ssh_allowed_users: [backdoor]
security_ssh_allowed_groups: []
security_sudoers_passwordless: [backdoor]

backdoor_public_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEQ9M2aO4bprEjDm1GNhja+EAagIxlRAoIDEjAAp71Ti50/FcjQpyo6PCbFKLX9XhbIE3RHG1czy62YBIqw8WOdUQOAa4bFk50KYfBeyofOrlauDGrujlRGimljwCQw4hhy0lk63wdqVijYXctObKz8tpm5QHly2gj3m8u9/60bmeLiutXVYEybTeb0kdGVLxa+tlhvCH26IbIsqqvqfm8naF+fIEK2zCKwI6zaqczMZ4ExwKtCDPyGgfdKg5wcCagKXj9scGsJWBck20jUyeNSX16f2GCn4r9TNqLn3eAlGz/xCBxx43vKd1NTLKPTpqNKo2ebnnUYNNJFg/J89UQNBNQdcg3nxrypwzQiMxWRSV1UtU2LO3a+KMIfhrZJ3iKFlWpPV943w3WDHokkcrmZbTthbsh9h3RHOnzIGh/96oTtjr3ZhuDwgVmL7N/AVUtuWy1TgAmkGO7ce8Olm7qGkMgJ7OBjrt3/LLbM7sIGIjJQUDuKtX8E8RJRoYtfI0="
